UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 1;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 2;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 3;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 4;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 5;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 6;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 7;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 8;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 9;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 10;
UPDATE articulos
	SET PRECIO_DESCUENTO = PRECIO * 0.9
	WHERE CODIGO = 11;