DELETE 
	FROM CAJAS 
	WHERE almacen = (SELECT A.codigo
		FROM ALMACENES A JOIN (SELECT * FROM CAJAS) AS BOX  ON (A.codigo = BOX.almacen)
        WHERE A.capacidad < 
			(SELECT COUNT(numReferencia) FROM ( SELECT * FROM CAJAS) AS BOXY));#LA AUTOREFERENCIABILIDAD DE TABLAS DEBE DE HACERSE SIEMPRE EXHORTANDO EL NOMBRE ORIGINAL, Y UN SELECT DE LA TOTALIDAD DE LA MISMA, ADEMAS DEL FROM Y EL AS QUE ASUMIRÁ EL NOMBRE DE LA TABLA
